services:
  flow.api:
    container_name: flow.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889"
      - "Serilog:WriteTo:3:Args:endpoint=http://aspire-dashboard:18889"
      - "Serilog:WriteTo:2:Args:serverUrl=http://seq:5341"
      - "DatabaseSettings:ConnectionString=Server=flow.db;Port=5432;Database=Flow;User Id=admin;Password=admin1234;"
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./.containers/logs:/app/logs

    depends_on:
      - flow.db
  
  flow.db:
    container_name: flow.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Flow
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=vladislavqlm@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=3535690
      - POSTGRES_DB=Flow
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8081:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  seq:
    container_name: seq
    environment:
      - "ACCEPT_EULA=Y"
    restart: always
    ports:
      - "5341:5341"
      - "8082:80"
    volumes:
      - seq_data:/data
  
  aspire-dashboard:
    container_name: aspire-dashboard
    environment:
      - "DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true"
    restart: always
    ports:
      - "18888:18888"
      - "4317:18889"