services:
  flow.api:
    image: ${DOCKER_REGISTRY-}flowapi
    build:
      context: .
      dockerfile: src/Flow.Api/Dockerfile

  flow.db:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce
  
  seq:
    image: datalust/seq:latest

volumes:
  postgres_data:
  pgadmin_data:
  portainer_data:
  seq_data:
