name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./Flow.sln

      - name: Build
        run: dotnet build ./Flow.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Flow.sln --configuration Release --no-restore --no-build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Flow.Api/Dockerfile
          push: true
          tags: vladislavqlm/flow:latest
